modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}" #mandatory

[[mods]]
    modId = "${mod_id}" #mandatory
    version = "${mod_version}" #mandatory
    # logoFile = "logo.png"  # Se você tiver um logo para o seu mod, especifique o caminho aqui.
    displayName = "${mod_name}" #mandatory
    description = '''${mod_description}''' #optional
    authors = "${mod_authors}" #optional
    credits = "${mod_credits}" #optional

[[dependencies.${mod_id}]]
    modId = "minecraft" #mandatory
    mandatory = true #mandatory
    versionRange = "${minecraft_version_range}" #mandatory
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "forge" #mandatory
    mandatory = true #mandatory
    versionRange = "${forge_version_range}" #mandatory
    side = "BOTH"

[[files]]
    modId = "${mod_id}" #optional
    fileId = "${mod_id}-${mod_version}.jar" #optional

